### ISSUE TITLE
Contributions

### ISSUE THREAD

**Issue by iainbrighton** [devblackops/NetScaler#1]
Hi @devblackops - I have some additions that I have added to the original Citrix module that I think could be added here (I see no point duplicating effort). Are you open to accepting external contributions, and if so, what process works for you?

**Comment by devblackops** [comment]
I'm absolutely open to contributions! 
I will try to come up with a formal policy similar to this: [https://github.com/PowerShell/DscResources/blob/master/CONTRIBUTING.md]

For now, a pull request with your changes will be great.

**Comment by devblackops** [comment]
CONTRIBUTING.md added. Looking forward to your contributions!
https://github.com/devblackops/NetScaler/blob/master/CONTRIBUTING.md

**Comment by iainbrighton** [comment]
Cool. Will take a look and start rewriting my functions to meet the requirements :)
