### ISSUE TITLE
Minor patch

### ISSUE THREAD

**Issue by psminion** [devblackops/NetScaler#15]
Hello @devblackops. I just submitted a pull request for a minor change (added a parameter alias) to the Get-NSLBServiceGroupMemberBinding function. Unfortunately I failed to read the CONTRIBUTING.md until after fact and did not run the pester tests prior to submitting the pull request. I'll try to do better in the future.

Love your module! I intend to be a heavy user and will try to contribute if I have any suggestions or run into any problems - in the unlikely event that your code isn't already perfect :)

**Comment by devblackops** [comment]
No worries and thanks for the PR! An AppVeyor build will kick off on any PR submissions but it's good to run `.\build.ps1 -task test` before hand. I only have Pester testing the module manifest, file encoding, and spaces/vs tabs at the moment. A bunch of work needs to be done on creation proper tests for the functions.

Any suggestions for improvements are welcome.
