### ISSUE TITLE
Add custom New-LBMonitor properties

### ISSUE THREAD

**Issue by iainbrighton** [devblackops/NetScaler#19]
When creating a monitor each different monitor type supports differing parameters/options. I would like see a `-CustomProperty` (or equivalent) parameter added to the `New-LBMonitor` cmdlet to allow passing custom monitor parameters.

## Possible Solution
Add parameter to pass custom parameters when creating a monitor, e.g.
```powershell
[Parameter()]
[System.Collections.Hashtable]$CustomProperty,
```
It would then be possible to pass any supported monitor parameter to the `New-LBMonitor` like so:
```powershell
New-LBMonitor -Session $ns -Name 'monitor_storefront_store' -Type STOREFRONT `
    -DestinationIP 10.11.12.13 -DestinationPort 443 -CustomProperty @{ Storename = 'Store' }
```
__I'm happy to submit a PR assuming the parameter naming is correct?__

**Comment by devblackops** [comment]
Sounds good to me. Are you thinking of having `New-NSLBMonitor` validate the custom properties for each monitor type before submitting to the API or relying on the NetScaler to validate after submission?

**Comment by iainbrighton** [comment]
I was planning on letting the NetScaler validate them! There are about 50 individual properties which would result in a mass of parameter sets. Maintaining it would probably be unmanageable :cry:

**Comment by devblackops** [comment]
Ya, dealing with multiple parameter sets is messy as it is 😄
