### ISSUE TITLE
New cmdlets

### ISSUE THREAD

**Issue by iainbrighton** [devblackops/NetScaler#20]
Now that I have some NetScaler work planned, I've started to look at merging in the additional cmdlets previously created to support our environments. This includes the following:

* **Get-NSVersion** - retrieve the NetScaler appliance version
* **Add-NSDnsSuffix** - Adds a DNS search suffix
* **New-NSSSLCertificateLink** - create SSL chain/root CA
* **New-NSLDAPAuthenticationAction** - create LDAP authentication action
* **New-NSLDAPAuthenticationPolicy** - create LDAP authentication policy
* **New-NSLBVirtualServerCertificateBinding** - bind a SSL certificate key pair to secure/HTTPS VIP
* **New-NSSSLProfile** - create a new SSL profile
* **New-NSVPNVirtualServer** - create a new VPN virtual server
* **New-NSVPNVirtualServerSessionAction** - create a new VPN session action
* **New-NSVPNVirtualServerSessionPolicy** - create a new VPN session policy
* **Add-NSVPNVirtualServerSessionPolicyBinding** - bind VPN session policy binding to VPN virtual server
* **Add-NSVPNVirtualServerSTAServerBinding** - add STA server bidning to VPN virtual server
* **Add-NSVPNVirtualServerCertificateBinding** - bind SSL certificate key pair to VPN virtual server
* **Set-NSVPNVirtualServerTheme** - configure a VPN virtual server theme

Apologies for not creating separate issues for each of them, but that seemed like additional, unnecessary work! Can you check that the naming of the cmdlets matches what you would expect?

**Comment by devblackops** [comment]
These look good to me. Thanks!
