### ISSUE TITLE
Add PFX support to Add-NSCertKeyPair

### ISSUE THREAD

**Issue by iainbrighton** [devblackops/NetScaler#21]
We use PFX certificates internally for NetScaler appliances. I would like to see PFX support added to the `Add-NSCertKeyPair` cmdlet.

## Expected Behavior
```powershell
Add-NSCertKeyPair -Session $ns -CertKeyName 'wildcard.lab.local' `
    -CertPath '/nsconfig/ssl/wildcard.lab.local.pfx' `
    -KeyPath '/nsconfig/ssl/wildcard.lab.local.pfx' -CertKeyFormat 'PFX' `
    -Password $privateKeyPassword
```

## Your Environment
* NetScaler version used: 11.0 and 11.1
* Module version used: 1.3.0
* Operating System and PowerShell version: Server 2012 R2 and 5.0.10586.117

**Comment by iainbrighton** [comment]
__I am happy to submit a PR for this if you would like me to?__

**Comment by devblackops** [comment]
Please do!
