### ISSUE TITLE
Fixes for new functions PR

### ISSUE THREAD

**Issue by psminion** [devblackops/NetScaler#25]
Brandon - What's the right way to submit the suggested corrections to the new AAA functions? Should I submit a new pull request with the updates? Or upload the files here? Or something else?

**Comment by devblackops** [comment]
You should be able to make the changes to your existing branch and push back to your fork on GitHub. Since the PR is still open, the changes will be reflected there.

http://stackoverflow.com/questions/9790448/how-to-update-a-pull-request

**Comment by devblackops** [comment]
Fixed in PR #24
