### ISSUE TITLE
New functions and additional parameters in existing functions

### ISSUE THREAD

**Issue by rokett** [devblackops/NetScaler#26]
Through using this module in a production environment there are a number of new functions I specifically need along with some additional parameters for existing functions.

## New functions
- Create a new Content Switching virtual server
- Add Content Switching virtual server responder policy binding
- Get Content Switching virtual server responder policy bindings
- Add SSL virtual server certificate binding
- Get SSL virtual server certificate bindings
- Add virtual server rewrite policy binding
- Get virtual server rewrite policy bindings
- Update SSL virtual server
- Get SSL virtual servers
- Add a monitor to a Service Group
- Get Service Group monitor bindings

## Additional parameters
- Add Persistence Type and Persistence Timeout to load balancing virtual server
- Add HTTP Request and expected Response Codes to the creation of a new load balancing monitor

## Bugs
- The NetScaler API reports an error when sending a request with the weight parameter when adding a virtual server service group binding.  The weight parameter needs to be moved to only be present when adding a service binding.

**Comment by devblackops** [comment]
Fixed in PR #27
