### ISSUE TITLE
Add redirect options when creating Virtual Server

### ISSUE THREAD

**Issue by rokett** [devblackops/NetScaler#35]
When creating a Virtual Server in the GUI it is possible to set a redirect.  For example browsing to http://mywebsite.com can be configured to redirect to https://mywebsite.com (or any other arbitrary URL).

## Expected Behavior
New-NSLBVirtualServer should allow for this configuration.

## Current Behavior
Parameters are not available to set this at the moment.

I have a fix for this; a pull request will be incoming shortly.

**Comment by devblackops** [comment]
Thanks for the addition!
