### ISSUE TITLE
Add icmpvsresponse parameter when creating new virtual servers

### ISSUE THREAD

**Issue by rokett** [devblackops/NetScaler#37]
The icmpvsresponse parameter allows you to set whether the the ICMP response is ACTIVE or PASSIVE.  Setting it to ACTIVE means that if the virtual server is down, the Netscaler will not respond to a ping request.  By default this is set to PASSIVE.

I have a patch for this for which I'll raise a pull request shortly.

## Current Behavior
No parameters are available to set this so the Netscaler defaults to all created Virtual Servers having a PASSIVE setting.

## Possible Solution
Add parameter to allow the setting to be customised by the user.  By default set it to PASSIVE to match what the Netscaler does.

## Context
In my configuration each virtual server has a unique IP address and when they are down I need the Netscaler to not respond to a ping request.

**Comment by devblackops** [comment]
This looks good to me. Thanks for the add!
