### ISSUE TITLE
Manifest.Tests.ps1 fails on change log version

### ISSUE THREAD

**Issue by dbroeglin** [devblackops/NetScaler#41]
When an _Unreleased_ version is present in the CHANGELOG.md file the "changelog and manifest versions are the same" test fails.

## Expected Behavior
It should work (ignore an unreleased version number)

## Current Behavior
It fails because it compares the unreleased version number (from CHANGELOG.md) and the manifest version.

## Possible Solution
Ignore the _unreleased_ version numbers in CHANGELOG.md

## Steps to Reproduce (for bugs)
Execute the unit tests.

**Comment by devblackops** [comment]
Fixed in PR #42
