### ISSUE TITLE
Add NSLB Responder Policy binding functions

### ISSUE THREAD

**Issue by rokett** [devblackops/NetScaler#43]
Functions already exists to add and get virtual server rewrite policy bindings.  This issue is about doing the same for responder policies.

## Expected Behavior
Should be able to add and get virtual server responder policy bindings.

## Current Behavior
Currently unavailable.

## Possible Solution
Two new functions to add and get responder policy bindings.

**Comment by devblackops** [comment]
Fixed in #44
