### ISSUE TITLE
URI protocol is script scoped

### ISSUE THREAD

**Issue by dbroeglin** [devblackops/NetScaler#76]
## Expected Behavior
The Nitro connection protocol should be associated with the session, not the `script` scope.

## Current Behavior
URI protocol is set as `$Script:protocol` in `Connect-Netscaler` but the IP is set in the connection object as then `Endpoint` property

## Possible Solution
Set the protocol on the session object and get it from there when needed.

What do you think ?

**Comment by devblackops** [comment]
That makes sense to me. `$script:protocol` should be moved to a property of the `$script:session` object.
