### ISSUE TITLE
Adding functions for PR

### ISSUE THREAD

**Issue by ryancbutler** [devblackops/NetScaler#82]
Created a fork with some additional functions and created an Issue to follow your guidelines for PRs.  Not sure if you want these split into multiple or if one is ok.

- Get-NSCurrentTime: Gets the current time from the Netscaler
- Get-NSlicenseExpiration: Reads license files found on the Netscaler and returns data around expiration
- Update-NSAppliance: Updates a Netscaler and uses firmware from a remote location

Let me know if this worth a PR or not.

**Comment by devblackops** [comment]
Yes! Definitely worth a PR. I'm OK with a single one for these.
